services:
  db:
    image: postgres:18
    container_name: galenai-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cruddb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - galenai_net

  app:
    build: .
    container_name: galenai-app
    depends_on:
      - db
    env_file:
      - galenfers/configs/.env
    ports:
      - "8080:8080"
    networks:
      - galenai_net

volumes:
  pgdata:

networks:
  galenai_net:
